### ISSUE TITLE
Replace Embedded Dart Sass with Dart Sass

### ISSUE THREAD

**Issue by ngdangtu-vn** [cloudflare/pages-build-image#7]
> **This is no longer the repository for Embedded Dart Sass.** The embedded
compiler has been merged into [the primary Dart Sass repository], and further
releases will be included [as part of Dart Sass itself]. The embedded compiler
can be accessed by running `sass --embedded`.

[Source](https://github.com/sass/dart-sass-embedded)

According to the official repo, the project was merged to the core. So I think it is better to use the new one.

For temporary solution, please update the [available version in the document](https://developers.cloudflare.com/pages/platform/language-support-and-tools) to max `1.62.1`.

**Comment by lennartzellmer** [comment]
Is there any plan to support the newer [dart-sass](https://github.com/sass/dart-sass) versions? I have issues with my deployment using sass-embedded with vite
